import mongoose from "mongoose";
import dotenv from "dotenv";
import TriviaQuestion from "./models/TriviaQuestion.js";

dotenv.config();

const MONGO_URI =
  "mongodb+srv://btechngng:Young6ix@cluster0.cwerqug.mongodb.net/ecommerce"; // or use process.env.MONGO_URI

const questions = [
  {
    question: "Who was the first executive president of Nigeria?",
    options: [
      "Nnamdi Azikiwe",
      "Shehu Shagari",
      "Obafemi Awolowo",
      "Yakubu Gowon",
    ],
    correctAnswer: "Shehu Shagari",
    category: "Politics",
  },
  {
    question: "Which Nigerian state is known as the 'Sunshine State'?",
    options: ["Ondo", "Osun", "Ekiti", "Kogi"],
    correctAnswer: "Ondo",
    category: "Geography",
  },
  {
    question: "Where is the Olumo Rock located?",
    options: ["Abeokuta", "Ibadan", "Oshogbo", "Ilorin"],
    correctAnswer: "Abeokuta",
    category: "Tourism",
  },
  {
    question: "Which Nigerian artist is known for the song 'Joro'?",
    options: ["Wizkid", "Davido", "Rema", "Olamide"],
    correctAnswer: "Wizkid",
    category: "Music",
  },
  {
    question: "What is the national motto of Nigeria?",
    options: [
      "Peace and Unity",
      "Unity and Faith, Peace and Progress",
      "Strength in Unity",
      "Justice and Progress",
    ],
    correctAnswer: "Unity and Faith, Peace and Progress",
    category: "National Identity",
  },
  {
    question: "Who is Nigeria’s Inspector General of Police as of 2023?",
    options: [
      "Mohammed Adamu",
      "Usman Alkali Baba",
      "Kayode Egbetokun",
      "Solomon Arase",
    ],
    correctAnswer: "Kayode Egbetokun",
    category: "Politics",
  },
  {
    question: "Which Nigerian city is known for its ancient walls?",
    options: ["Kano", "Ilorin", "Benin City", "Zaria"],
    correctAnswer: "Benin City",
    category: "History",
  },
  {
    question: "Which state is referred to as the 'Food Basket of the Nation'?",
    options: ["Benue", "Kano", "Kaduna", "Ebonyi"],
    correctAnswer: "Benue",
    category: "Agriculture",
  },
  {
    question: "Who directed 'King of Boys'?",
    options: ["Kemi Adetiba", "Kunle Afolayan", "Mo Abudu", "Genevieve Nnaji"],
    correctAnswer: "Kemi Adetiba",
    category: "Entertainment",
  },
  {
    question: "Which Nigerian city is the capital of Kwara State?",
    options: ["Ilorin", "Lokoja", "Minna", "Jebba"],
    correctAnswer: "Ilorin",
    category: "Geography",
  },
  {
    question: "Which ethnic group is predominant in Cross River State?",
    options: ["Efik", "Igbo", "Yoruba", "Hausa"],
    correctAnswer: "Efik",
    category: "Culture",
  },
  {
    question: "What is the name of Nigeria’s legislative building?",
    options: [
      "Aso Villa",
      "Eagle Square",
      "National Assembly",
      "Supreme Court",
    ],
    correctAnswer: "National Assembly",
    category: "Politics",
  },
  {
    question: "Which Nigerian footballer is nicknamed 'Jay-Jay'?",
    options: ["Obafemi Martins", "Jay-Jay Okocha", "Nwankwo Kanu", "Mikel Obi"],
    correctAnswer: "Jay-Jay Okocha",
    category: "Sports",
  },
  {
    question:
      "Where is the headquarters of the Economic and Financial Crimes Commission (EFCC)?",
    options: ["Lagos", "Abuja", "Benin", "Kano"],
    correctAnswer: "Abuja",
    category: "Politics",
  },
  {
    question: "Which Nigerian writer authored 'Purple Hibiscus'?",
    options: ["Chimamanda Adichie", "Sefi Atta", "Ben Okri", "Buchi Emecheta"],
    correctAnswer: "Chimamanda Adichie",
    category: "Literature",
  },
  {
    question: "Which river separates Nigeria and Niger Republic?",
    options: ["River Niger", "River Sokoto", "River Kaduna", "River Benue"],
    correctAnswer: "River Niger",
    category: "Geography",
  },
  {
    question: "Which city is referred to as the ‘Tin City’?",
    options: ["Jos", "Kano", "Zaria", "Kaduna"],
    correctAnswer: "Jos",
    category: "Economy",
  },
  {
    question:
      "Which Nigerian traditional festival is associated with boat regattas?",
    options: ["Argungu", "Eyo", "Osun-Osogbo", "Ofala"],
    correctAnswer: "Argungu",
    category: "Culture",
  },
  {
    question: "Who is the traditional ruler of the Yoruba people?",
    options: ["Igwe", "Obong", "Oba", "Emir"],
    correctAnswer: "Oba",
    category: "Culture",
  },
  {
    question: "Who is considered the founder of modern Lagos?",
    options: [
      "King Kosoko",
      "Oba Akitoye",
      "Frederick Lugard",
      "Bishop Ajayi Crowther",
    ],
    correctAnswer: "Oba Akitoye",
    category: "History",
  },
  {
    question: "What is the name of the national stadium located in Abuja?",
    options: [
      "Eagle Stadium",
      "National Stadium Abuja",
      "Moshood Abiola Stadium",
      "Unity Arena",
    ],
    correctAnswer: "Moshood Abiola Stadium",
    category: "Sports",
  },
  {
    question: "Which state in Nigeria is popular for groundnut pyramids?",
    options: ["Kano", "Sokoto", "Zamfara", "Niger"],
    correctAnswer: "Kano",
    category: "Agriculture",
  },
  {
    question: "Which popular Nigerian actress is also a politician?",
    options: ["Genevieve Nnaji", "Ini Edo", "Funke Akindele", "Omotola Jalade"],
    correctAnswer: "Funke Akindele",
    category: "Entertainment",
  },
  {
    question: "Which Nigerian city is home to the Zuma Rock?",
    options: ["Abuja", "Minna", "Lokoja", "Suleja"],
    correctAnswer: "Suleja",
    category: "Geography",
  },
  {
    question: "Which company is Nigeria’s largest mobile network provider?",
    options: ["MTN", "Glo", "Airtel", "9mobile"],
    correctAnswer: "MTN",
    category: "Technology",
  },
  {
    question: "What is the main material used in Aso Oke traditional wear?",
    options: ["Cotton", "Wool", "Silk", "Denim"],
    correctAnswer: "Cotton",
    category: "Culture",
  },
  {
    question: "Which sport is Nigeria most successful in at the Olympics?",
    options: ["Boxing", "Wrestling", "Athletics", "Football"],
    correctAnswer: "Football",
    category: "Sports",
  },
  {
    question: "What’s the capital of Bauchi State?",
    options: ["Gombe", "Bauchi", "Jalingo", "Damaturu"],
    correctAnswer: "Bauchi",
    category: "Geography",
  },
  {
    question:
      "Which Nigerian is known as the 'Father of the Internet' in Africa?",
    options: [
      "Philip Emeagwali",
      "Mike Adenuga",
      "Leo Stan Ekeh",
      "Mitchell Elegbe",
    ],
    correctAnswer: "Philip Emeagwali",
    category: "Technology",
  },
  {
    question: "Who founded the Nigerian Stock Exchange?",
    options: [
      "Aliko Dangote",
      "Oba Otudeko",
      "Akintola Williams",
      "Tony Elumelu",
    ],
    correctAnswer: "Akintola Williams",
    category: "Economy",
  },
  {
    question: "Which city hosts the annual Lagos Black Heritage Festival?",
    options: ["Lagos", "Calabar", "Benin", "Jos"],
    correctAnswer: "Calabar",
    category: "Culture",
  },
  {
    question: "Which river flows through Onitsha and Warri?",
    options: ["River Niger", "River Benue", "River Anambra", "River Osun"],
    correctAnswer: "River Niger",
    category: "Geography",
  },
  {
    question:
      "Which Nigerian state is famous for the Argungu Fishing Festival?",
    options: ["Kebbi", "Sokoto", "Kano", "Kaduna"],
    correctAnswer: "Kebbi",
    category: "Culture",
  },
  {
    question: "Who was the first female head of state in Nigeria (acting)?",
    options: [
      "Ireti Kingibe",
      "Maryam Babangida",
      "Nana Shettima",
      "Sarah Jubril",
    ],
    correctAnswer: "Ireti Kingibe",
    category: "Politics",
  },
  {
    question: "Which Nigerian airline ceased operations in 2019?",
    options: ["Arik Air", "Dana Air", "Air Nigeria", "Bellview"],
    correctAnswer: "Air Nigeria",
    category: "Economy",
  },
  {
    question: "Which musician won a Grammy for the song 'Essence'?",
    options: ["Wizkid", "Davido", "Burna Boy", "Tiwa Savage"],
    correctAnswer: "Wizkid",
    category: "Music",
  },
  {
    question: "Where was the first standard gauge railway in Nigeria built?",
    options: [
      "Lagos‑Ibadan",
      "Abuja‑Kaduna",
      "Port Harcourt‑Maiduguri",
      "Enugu‑Warri",
    ],
    correctAnswer: "Lagos‑Ibadan",
    category: "Infrastructure",
  },
  {
    question: "Who established the Calabar Light Rail in 2023?",
    options: [
      "Gov. Umo Eno",
      "Gov. Ben Ayade",
      "Gov. Seriake Dickson",
      "Gov. Emmanuel Udom",
    ],
    correctAnswer: "Gov. Umo Eno",
    category: "Politics",
  },
  {
    question: "Which Nigerian state has the largest grape farm?",
    options: ["Nasarawa", "Kaduna", "Oyo", "Kebbi"],
    correctAnswer: "Nasarawa",
    category: "Agriculture",
  },
  {
    question: "Which area in Lagos is known as the tech startup hub?",
    options: ["Lekki", "Yaba", "Victoria Island", "Ikeja"],
    correctAnswer: "Yaba",
    category: "Technology",
  },
  {
    question: "Which Nigerian author wrote 'Half of a Yellow Sun'?",
    options: [
      "Ben Okri",
      "Wole Soyinka",
      "Chimamanda Adichie",
      "Chinua Achebe",
    ],
    correctAnswer: "Chimamanda Adichie",
    category: "Literature",
  },
  {
    question: "Which Nigerian city lies on the Benue–Niger confluence?",
    options: ["Lokoja", "Lokoja", "Lokoja", "Lokoja"], // trick repeating
    correctAnswer: "Lokoja",
    category: "Geography",
  },
  {
    question: "Who invented the first Nigerian satellite?",
    options: [
      "Ngozi Okonjo‑Iweala",
      "Arinola Olayiwola",
      "Dr. Obiageli Ezeilo",
      "Prof. Akindele Ajayi",
    ],
    correctAnswer: "Arinola Olayiwola",
    category: "Science",
  },
  {
    question: "Which book won the Nigeria Prize for Literature in 2020?",
    options: [
      "Lanterns of the Kingdom",
      "My Name Is Not Olosho",
      "Contemporary Musings",
      "Chasing Shadows",
    ],
    correctAnswer: "Lanterns of the Kingdom",
    category: "Literature",
  },
  {
    question:
      "Which Nigerian state is home to the Aso Rock Presidential Villa?",
    options: ["FCT", "Kaduna", "Plateau", "Niger"],
    correctAnswer: "FCT",
    category: "Politics",
  },
  {
    question: "Which sport is Nigeria's Precious Achiuwa associated with?",
    options: ["Basketball", "Football", "Boxing", "Wrestling"],
    correctAnswer: "Basketball",
    category: "Sports",
  },
  {
    question: "Who directed the movie 'Lionheart' on Netflix?",
    options: [
      "Kunle Afolayan",
      "Genevieve Nnaji",
      "Tunde Kelani",
      "Izu Ojukwu",
    ],
    correctAnswer: "Genevieve Nnaji",
    category: "Film",
  },
  {
    question: "Which city is famous for the Eyo masquerade?",
    options: ["Lagos", "Ibadan", "Asaba", "Enugu"],
    correctAnswer: "Lagos",
    category: "Culture",
  },
  {
    question: "What animal symbolizes Nigeria's unity on the Coat of Arms?",
    options: ["White horse", "Eagle", "Lion", "Bull"],
    correctAnswer: "White horse",
    category: "Nationhood",
  },
  {
    question: "Which Nigerian bank launched ALAT?",
    options: ["Wema Bank", "GTBank", "Zenith Bank", "Access Bank"],
    correctAnswer: "Wema Bank",
    category: "Economy",
  },
  {
    question: "Which era did Nigeria spend under British rule?",
    options: ["1901–1960", "1861–1950", "1905–1963", "1920–1960"],
    correctAnswer: "1901–1960",
    category: "History",
  },
  {
    question: "Which Nigerian writer won the Man Booker Prize?",
    options: [
      "Chinua Achebe",
      "Ben Okri",
      "Ama Ata Aidoo",
      "Chimamanda Adichie",
    ],
    correctAnswer: "Ben Okri",
    category: "Literature",
  },
  {
    question: "Which northern Nigerian city is known for leather markets?",
    options: ["Kano", "Sokoto", "Maiduguri", "Zaria"],
    correctAnswer: "Kano",
    category: "Economy",
  },
  {
    question:
      "Which festival includes masquerades and canoe regatta in Calabar?",
    options: [
      "Carnival",
      "Calabar Festival",
      "Eyo Festival",
      "Argungu Festival",
    ],
    correctAnswer: "Calabar Festival",
    category: "Culture",
  },
  {
    question: "Who formulated Nigeria's Vision 2020 roadmap?",
    options: ["Obasanjo", "Jonathan", "Buhari", "Tinubu"],
    correctAnswer: "Obasanjo",
    category: "Politics",
  },
  {
    question: "Which company produced the first Nigerian-made car?",
    options: [
      "Innoson Motors",
      "Dangote Motors",
      "Max Motors",
      "Zenith Motors",
    ],
    correctAnswer: "Innoson Motors",
    category: "Economy",
  },
  {
    question: "Which state is home to the Rajumalchi Wildlife Sanctuary?",
    options: ["Kaduna", "Bauchi", "Taraba", "Benue"],
    correctAnswer: "Kaduna",
    category: "Nature",
  },
  {
    question: "Which Nigerian state celebrates the Ofala festival annually?",
    options: ["Anambra", "Enugu", "Lagos", "Imo"],
    correctAnswer: "Anambra",
    category: "Culture",
  },
  {
    question: "Which street in Lagos is known for electronics markets?",
    options: [
      "Broad Street",
      "Computer Village",
      "Tejuosho Lane",
      "Ikeja City Mall",
    ],
    correctAnswer: "Computer Village",
    category: "Economy",
  },
  {
    question: "Which traditional language uses Nsibidi script?",
    options: ["Igbo", "Efik", "Yoruba", "Hausa"],
    correctAnswer: "Efik",
    category: "Language",
  },
  {
    question: "Which bank was Nigeria's first?",
    options: ["Union Bank", "First Bank", "Zenith Bank", "Access Bank"],
    correctAnswer: "First Bank",
    category: "Economy",
  },
  {
    question: "Which state has the longest coastline in Nigeria?",
    options: ["Rivers", "Bayelsa", "Lagos", "Edo"],
    correctAnswer: "Bayelsa",
    category: "Geography",
  },
  {
    question: "What is Nigeria’s tallest building as of 2025?",
    options: ["NECOM House", "Eko Tower", "Ikeja City Mall", "Civic Center"],
    correctAnswer: "NECOM House",
    category: "Architecture",
  },
  {
    question:
      "Which Nigerian sportsperson won silver in boxing at the Olympics?",
    options: ["Audu Adamu", "Efe Ajagba", "Daniel Igali", "Noah Ikpe"],
    correctAnswer: "Audu Adamu",
    category: "Sports",
  },
  {
    question: "Which festival features canoe racing in the Lagos lagoon?",
    options: ["Carnival", "Calabar Festival", "Eyo Festival", "Ofala"],
    correctAnswer: "Eyo Festival",
    category: "Culture",
  },
  {
    question: "Which Nigerian state is the largest producer of cocoa?",
    options: ["Ondo", "Oyo", "Ekiti", "Osun"],
    correctAnswer: "Ondo",
    category: "Economy",
  },
  {
    question: "Which language is spoken predominantly in Taraba State?",
    options: ["Fulfulde", "Efik", "Yoruba", "Igbo"],
    correctAnswer: "Fulfulde",
    category: "Language",
  },
  {
    question: "Who is Nigeria’s first Nobel Laureate?",
    options: ["Wole Soyinka", "Chinua Achebe", "Nnamdi Azikiwe", "Ben Okri"],
    correctAnswer: "Wole Soyinka",
    category: "Literature",
  },
  {
    question: "Which state is known for its waterfall at Omambala River?",
    options: ["Anambra", "Enugu", "Kaduna", "Oyo"],
    correctAnswer: "Anambra",
    category: "Tourism",
  },
  {
    question: "Which troop was Nigeria’s peacekeeping force named?",
    options: ["NAFPEACE", "NAFECOM", "NIGPEACE", "N-Peace"],
    correctAnswer: "NAFPEACE",
    category: "Military",
  },
  {
    question: "Which cultural attire features the 'Isi Agu' design?",
    options: [
      "Igbo traditional",
      "Yoruba agbada",
      "Hausa babanriga",
      "Efik wrapper",
    ],
    correctAnswer: "Igbo traditional",
    category: "Culture",
  },
  {
    question: "Which government initiative is 'N-POWER' under?",
    options: [
      "Presidential",
      "National",
      "Youth Support",
      "Labour & Employment",
    ],
    correctAnswer: "Presidential",
    category: "Politics",
  },
  {
    question: "Which region leads Nigeria in rice production?",
    options: ["Northern", "Western", "Eastern", "Southern"],
    correctAnswer: "Northern",
    category: "Agriculture",
  },
  {
    question: "Which Nigerian state is known as the 'Gateway State'?",
    options: ["Lagos", "Ogun", "Ondo", "Ekiti"],
    correctAnswer: "Ogun",
    category: "Geography",
  },
  {
    question: "Who composed the Nigerian national anthem?",
    options: [
      "Benedict E. Odiase",
      "Wole Soyinka",
      "Chinua Achebe",
      "Sani Abacha",
    ],
    correctAnswer: "Benedict E. Odiase",
    category: "History",
  },
  {
    question: "Which Nigerian city is famous for leather production?",
    options: ["Kano", "Onitsha", "Benin", "Calabar"],
    correctAnswer: "Kano",
    category: "Economy",
  },
  {
    question: "What is the staple food made from cassava in Nigeria?",
    options: ["Rice", "Fufu", "Tuwo", "Eba"],
    correctAnswer: "Eba",
    category: "Culture",
  },
  {
    question: "Which mountain is located on the Mambilla Plateau?",
    options: ["Mount Patti", "Obudu", "Chappal Waddi", "Mandara"],
    correctAnswer: "Chappal Waddi",
    category: "Geography",
  },
  {
    question: "Which ethnic group is dominant in Sokoto State?",
    options: ["Hausa", "Yoruba", "Igbo", "Efik"],
    correctAnswer: "Hausa",
    category: "Culture",
  },
  {
    question: "What does EFCC stand for?",
    options: [
      "Economic and Financial Crimes Commission",
      "Electricity and Fuel Control Council",
      "Emergency Fund for Crime Control",
      "None of the above",
    ],
    correctAnswer: "Economic and Financial Crimes Commission",
    category: "General Knowledge",
  },
  {
    question: "What is the Nigerian Senate chamber color?",
    options: ["Red", "Blue", "Green", "White"],
    correctAnswer: "Red",
    category: "Politics",
  },
  {
    question: "Which Nigerian artist is known as 'Starboy'?",
    options: ["Davido", "Wizkid", "Olamide", "Burna Boy"],
    correctAnswer: "Wizkid",
    category: "Entertainment",
  },
  {
    question: "Which northern Nigerian festival involves horse riding?",
    options: ["Argungu", "Durbar", "Osun-Osogbo", "Ofala"],
    correctAnswer: "Durbar",
    category: "Culture",
  },
  {
    question: "What is the primary export of Nigeria?",
    options: ["Cocoa", "Palm oil", "Oil", "Cotton"],
    correctAnswer: "Oil",
    category: "Economy",
  },
  {
    question: "Which Nigerian tribe is known for talking drums?",
    options: ["Igbo", "Yoruba", "Hausa", "Itsekiri"],
    correctAnswer: "Yoruba",
    category: "Culture",
  },
  {
    question: "Who is the first female Speaker of Nigeria's House of Reps?",
    options: [
      "Stella Oduah",
      "Ngozi Okonjo-Iweala",
      "Patricia Etteh",
      "Kemi Adeosun",
    ],
    correctAnswer: "Patricia Etteh",
    category: "Politics",
  },
  {
    question: "Which Nigerian tribe is known for bronze sculptures?",
    options: ["Igbo", "Yoruba", "Benin", "Ijaw"],
    correctAnswer: "Benin",
    category: "Art",
  },
  {
    question: "Which sea borders Nigeria to the south?",
    options: ["Mediterranean Sea", "Red Sea", "Atlantic Ocean", "Indian Ocean"],
    correctAnswer: "Atlantic Ocean",
    category: "Geography",
  },
  {
    question: "Which Nigerian sportsperson won Olympic gold in 2000?",
    options: [
      "Chioma Ajunwa",
      "Falilat Ogunkoya",
      "Blessing Okagbare",
      "Mary Onyali",
    ],
    correctAnswer: "Chioma Ajunwa",
    category: "Sports",
  },
  {
    question: "Which state has the slogan 'Land of Promise'?",
    options: ["Akwa Ibom", "Bayelsa", "Cross River", "Delta"],
    correctAnswer: "Akwa Ibom",
    category: "Geography",
  },
  {
    question: "Which body regulates universities in Nigeria?",
    options: ["WAEC", "JAMB", "NYSC", "NUC"],
    correctAnswer: "NUC",
    category: "Education",
  },
  {
    question: "What is the highest court in Nigeria?",
    options: [
      "High Court",
      "Appeal Court",
      "Supreme Court",
      "Magistrate Court",
    ],
    correctAnswer: "Supreme Court",
    category: "Law",
  },
  {
    question: "Which city is home to Obafemi Awolowo University?",
    options: ["Ibadan", "Ile-Ife", "Abeokuta", "Akure"],
    correctAnswer: "Ile-Ife",
    category: "Education",
  },
  {
    question: "Which Nigerian state is known for groundnut pyramids?",
    options: ["Kano", "Kaduna", "Sokoto", "Katsina"],
    correctAnswer: "Kano",
    category: "History",
  },
  {
    question: "Which tribe uses the 'Ekpe' masquerade?",
    options: ["Yoruba", "Efik", "Igbo", "Tiv"],
    correctAnswer: "Efik",
    category: "Culture",
  },
  {
    question: "Which Nigerian writer authored 'Purple Hibiscus'?",
    options: [
      "Chinua Achebe",
      "Ben Okri",
      "Chimamanda Adichie",
      "Helon Habila",
    ],
    correctAnswer: "Chimamanda Adichie",
    category: "Literature",
  },
  {
    question: "Which Nigerian city is a major film production hub?",
    options: ["Kano", "Enugu", "Asaba", "Jos"],
    correctAnswer: "Asaba",
    category: "Entertainment",
  },
  {
    question: "Who is Nigeria’s Chief of Defense Staff as of 2024?",
    options: [
      "Lucky Irabor",
      "Christopher Musa",
      "Ibrahim Attahiru",
      "Tukur Buratai",
    ],
    correctAnswer: "Christopher Musa",
    category: "Military",
  },
  {
    question: "Which state is nicknamed 'Heartbeat of the Nation'?",
    options: ["Edo", "Delta", "Anambra", "Osun"],
    correctAnswer: "Edo",
    category: "Geography",
  },
  {
    question: "What year was Nigeria declared a republic?",
    options: ["1960", "1963", "1970", "1999"],
    correctAnswer: "1963",
    category: "History",
  },
  {
    question: "Which sport is Dambe associated with?",
    options: ["Boxing", "Wrestling", "Martial Arts", "Fencing"],
    correctAnswer: "Boxing",
    category: "Sports",
  },
  {
    question: "What is the name of Nigeria’s electoral body?",
    options: ["INEC", "INEA", "ECOWAS", "NEPA"],
    correctAnswer: "INEC",
    category: "Politics",
  },
  {
    question: "Who founded the Nigerian Stock Exchange?",
    options: [
      "Aliko Dangote",
      "Obafemi Awolowo",
      "Jubril Aminu",
      "Akintola Williams",
    ],
    correctAnswer: "Akintola Williams",
    category: "Economy",
  },
  {
    question: "Which region was first to produce oil in Nigeria?",
    options: ["Delta", "Bayelsa", "Rivers", "Ondo"],
    correctAnswer: "Bayelsa",
    category: "Economy",
  },
  {
    question: "What does 'BRT' stand for in Lagos transport?",
    options: [
      "Bus Rapid Transit",
      "Basic Road Transport",
      "Broad Route Track",
      "Big Road Transit",
    ],
    correctAnswer: "Bus Rapid Transit",
    category: "Transport",
  },
  {
    question: "Which Nigerian dish is made from beans and steamed?",
    options: ["Moi Moi", "Akara", "Okpa", "Amala"],
    correctAnswer: "Moi Moi",
    category: "Food",
  },
  {
    question: "Who painted 'Tutu', a famous Nigerian artwork?",
    options: [
      "Ben Enwonwu",
      "Nike Davies-Okundaye",
      "Bruce Onobrakpeya",
      "Yusuf Grillo",
    ],
    correctAnswer: "Ben Enwonwu",
    category: "Art",
  },
  {
    question: "Which state is associated with the Ofala Festival?",
    options: ["Anambra", "Imo", "Delta", "Abia"],
    correctAnswer: "Anambra",
    category: "Culture",
  },
  {
    question: "Which is the largest university in Nigeria by enrollment?",
    options: [
      "University of Ibadan",
      "Ahmadu Bello University",
      "National Open University of Nigeria",
      "UNILAG",
    ],
    correctAnswer: "National Open University of Nigeria",
    category: "Education",
  },
  {
    question: "What year did Nigeria adopt the naira as its currency?",
    options: ["1973", "1960", "1980", "1990"],
    correctAnswer: "1973",
    category: "Economy",
  },
  {
    question: "Who is considered the first Nigerian female pilot?",
    options: [
      "Chinyere Kalu",
      "Tolulope Arotile",
      "Stella Adadevoh",
      "Ngozi Okonjo-Iweala",
    ],
    correctAnswer: "Chinyere Kalu",
    category: "History",
  },
  {
    question: "Which river forms a boundary between Nigeria and Cameroon?",
    options: ["Benue", "Cross", "Niger", "Gongola"],
    correctAnswer: "Cross",
    category: "Geography",
  },
  {
    question: "Who is the current Ooni of Ife?",
    options: [
      "Oba Adeyeye Enitan Ogunwusi",
      "Oba Akiolu",
      "Oba Elegushi",
      "Oba Sijuade",
    ],
    correctAnswer: "Oba Adeyeye Enitan Ogunwusi",
    category: "Culture",
  },
  {
    question: "Which Nigerian city hosts the Calabar Carnival?",
    options: ["Lagos", "Uyo", "Calabar", "Port Harcourt"],
    correctAnswer: "Calabar",
    category: "Culture",
  },
  {
    question: "Which oil company discovered oil in Nigeria?",
    options: ["Shell", "Chevron", "ExxonMobil", "Total"],
    correctAnswer: "Shell",
    category: "Economy",
  },
  {
    question: "What’s the local name for millet in Hausa?",
    options: ["Gero", "Tuwo", "Oka", "Agbado"],
    correctAnswer: "Gero",
    category: "Language",
  },
  {
    question: "What does 'Sambisa' refer to?",
    options: ["A forest", "A lake", "A mountain", "A border town"],
    correctAnswer: "A forest",
    category: "Geography",
  },
  {
    question: "Who was Nigeria's first military Head of State?",
    options: [
      "Yakubu Gowon",
      "Aguiyi Ironsi",
      "Olusegun Obasanjo",
      "Ibrahim Babangida",
    ],
    correctAnswer: "Aguiyi Ironsi",
    category: "History",
  },
  {
    question: "Which state is known for the Yankari Game Reserve?",
    options: ["Bauchi", "Taraba", "Kogi", "Benue"],
    correctAnswer: "Bauchi",
    category: "Tourism",
  },
  {
    question: "What is the capital of Nigeria?",
    options: ["Lagos", "Abuja", "Kano", "Enugu"],
    correctAnswer: "Abuja",
    category: "Geography",
  },
  {
    question: "Who was Nigeria's first president?",
    options: [
      "Nnamdi Azikiwe",
      "Olusegun Obasanjo",
      "Goodluck Jonathan",
      "Yakubu Gowon",
    ],
    correctAnswer: "Nnamdi Azikiwe",
    category: "History",
  },
  {
    question: "In what year did Nigeria gain independence?",
    options: ["1960", "1956", "1963", "1970"],
    correctAnswer: "1960",
    category: "History",
  },
  {
    question: "Which is Nigeria’s most populous city?",
    options: ["Kano", "Ibadan", "Lagos", "Port Harcourt"],
    correctAnswer: "Lagos",
    category: "Geography",
  },
  {
    question: "What is the official language of Nigeria?",
    options: ["Igbo", "Yoruba", "English", "Hausa"],
    correctAnswer: "English",
    category: "Culture",
  },
  {
    question: "Which river is the longest in Nigeria?",
    options: ["River Benue", "River Ogun", "River Niger", "River Osun"],
    correctAnswer: "River Niger",
    category: "Geography",
  },
  {
    question: "Which currency is used in Nigeria?",
    options: ["Dollar", "Naira", "Cedi", "Shilling"],
    correctAnswer: "Naira",
    category: "General Knowledge",
  },
  {
    question: "What is Nigeria’s international dialing code?",
    options: ["+256", "+234", "+233", "+221"],
    correctAnswer: "+234",
    category: "General Knowledge",
  },
  {
    question: "How many states does Nigeria have?",
    options: ["30", "32", "36", "38"],
    correctAnswer: "36",
    category: "General Knowledge",
  },
  {
    question: "Which Nigerian musician is known as 'Fela'?",
    options: ["Fela Kuti", "Wizkid", "Davido", "Burna Boy"],
    correctAnswer: "Fela Kuti",
    category: "Music",
  },
  {
    question: "Which state is known as the 'Coal City'?",
    options: ["Enugu", "Kaduna", "Jos", "Benin"],
    correctAnswer: "Enugu",
    category: "Geography",
  },
  {
    question: "Which Nigerian author wrote 'Things Fall Apart'?",
    options: [
      "Chimamanda Adichie",
      "Chinua Achebe",
      "Wole Soyinka",
      "Ben Okri",
    ],
    correctAnswer: "Chinua Achebe",
    category: "Literature",
  },
  {
    question: "Which Nigerian state is famous for oil production?",
    options: ["Lagos", "Kano", "Rivers", "Oyo"],
    correctAnswer: "Rivers",
    category: "Economy",
  },
  {
    question: "What does 'NYSC' stand for?",
    options: [
      "National Youth Service Corps",
      "Nigerian Young Students' Club",
      "National Youth Sports Club",
      "None of the above",
    ],
    correctAnswer: "National Youth Service Corps",
    category: "General Knowledge",
  },
  {
    question: "Which Nigerian won the Nobel Prize for Literature?",
    options: [
      "Chinua Achebe",
      "Wole Soyinka",
      "Chimamanda Adichie",
      "Ben Okri",
    ],
    correctAnswer: "Wole Soyinka",
    category: "Literature",
  },
  {
    question: "Where is the Zuma Rock located?",
    options: ["Abuja", "Niger State", "Kogi", "Kaduna"],
    correctAnswer: "Niger State",
    category: "Geography",
  },
  {
    question: "Which Nigerian city is known as the 'Centre of Excellence'?",
    options: ["Abuja", "Lagos", "Ibadan", "Jos"],
    correctAnswer: "Lagos",
    category: "Geography",
  },
  {
    question: "What is the dominant religion in northern Nigeria?",
    options: ["Christianity", "Islam", "Traditional", "Hinduism"],
    correctAnswer: "Islam",
    category: "Culture",
  },
  {
    question: "Which local government is the largest in Nigeria?",
    options: ["Obio-Akpor", "Alimosho", "Ikeja", "Gwale"],
    correctAnswer: "Alimosho",
    category: "Geography",
  },
  {
    question: "Who is known as the 'Zik of Africa'?",
    options: [
      "Olusegun Obasanjo",
      "Ahmadu Bello",
      "Nnamdi Azikiwe",
      "Tafawa Balewa",
    ],
    correctAnswer: "Nnamdi Azikiwe",
    category: "History",
  },
  {
    question: "What is Nigeria’s currency called?",
    options: ["Dollar", "Cedi", "Naira", "Shilling"],
    correctAnswer: "Naira",
    category: "Economy",
  },
  {
    question: "Which Nigerian artist sang 'Fall'?",
    options: ["Burna Boy", "Davido", "Wizkid", "Olamide"],
    correctAnswer: "Davido",
    category: "Entertainment",
  },
  {
    question: "What color is the Nigerian flag?",
    options: [
      "Green, White, Green",
      "Red, White, Blue",
      "Green and Yellow",
      "Blue and White",
    ],
    correctAnswer: "Green, White, Green",
    category: "General Knowledge",
  },
  {
    question: "Which river is the longest in Nigeria?",
    options: ["River Benue", "River Ogun", "River Niger", "River Osun"],
    correctAnswer: "River Niger",
    category: "Geography",
  },
  {
    question: "Which year was the Nigerian Civil War?",
    options: ["1966", "1967", "1970", "1975"],
    correctAnswer: "1967",
    category: "History",
  },
  {
    question: "Which state is known as the 'Centre of Excellence'?",
    options: ["Abuja", "Kano", "Lagos", "Ogun"],
    correctAnswer: "Lagos",
    category: "Geography",
  },
  {
    question: "What is the name of Nigeria’s national anthem?",
    options: [
      "Rise and Shine",
      "Arise O Compatriots",
      "Nigeria My Country",
      "Lift Up Your Heads",
    ],
    correctAnswer: "Arise O Compatriots",
    category: "Culture",
  },
  {
    question: "Who is known as the 'Lion of Bourdillon'?",
    options: [
      "Goodluck Jonathan",
      "Atiku Abubakar",
      "Muhammadu Buhari",
      "Bola Ahmed Tinubu",
    ],
    correctAnswer: "Bola Ahmed Tinubu",
    category: "Politics",
  },
  {
    question: "Which university is the oldest in Nigeria?",
    options: [
      "University of Lagos",
      "Ahmadu Bello University",
      "University of Nigeria, Nsukka",
      "University of Ibadan",
    ],
    correctAnswer: "University of Ibadan",
    category: "Education",
  },
  {
    question: "What is the local name for corn in Yoruba?",
    options: ["Agbado", "Oka", "Masara", "Ogi"],
    correctAnswer: "Agbado",
    category: "Language",
  },
  {
    question:
      "Which Nigerian team won the 1996 Olympic gold medal in football?",
    options: ["Super Falcons", "Dream Team", "Golden Eaglets", "Super Eagles"],
    correctAnswer: "Dream Team",
    category: "Sports",
  },
  {
    question: "Who founded the Sokoto Caliphate?",
    options: [
      "Usman dan Fodio",
      "Ahmadu Bello",
      "Shehu Shagari",
      "Sardauna of Sokoto",
    ],
    correctAnswer: "Usman dan Fodio",
    category: "History",
  },
  {
    question: "Which Nollywood actor is nicknamed ‘Mr. Ibu’?",
    options: [
      "Osita Iheme",
      "John Okafor",
      "Chinedu Ikedieze",
      "Kanayo O Kanayo",
    ],
    correctAnswer: "John Okafor",
    category: "Entertainment",
  },
  {
    question: "How many geopolitical zones are in Nigeria?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "6",
    category: "Geography",
  },
  {
    question: "Which festival is celebrated by the Yoruba people?",
    options: ["Durbar", "Argungu", "Osun-Osogbo", "Ofala"],
    correctAnswer: "Osun-Osogbo",
    category: "Culture",
  },
  {
    question: "What is the name of Nigeria’s Senate President as of 2023?",
    options: [
      "Ahmed Lawan",
      "Femi Gbajabiamila",
      "Godswill Akpabio",
      "Bukola Saraki",
    ],
    correctAnswer: "Godswill Akpabio",
    category: "Politics",
  },
  {
    question: "What is the traditional attire of the Igbo people?",
    options: ["Agbada", "Isi Agu", "Dashiki", "Buba"],
    correctAnswer: "Isi Agu",
    category: "Culture",
  },
  {
    question: "Which Nigerian musician won a Grammy in 2021?",
    options: ["Davido", "Wizkid", "Burna Boy", "Tems"],
    correctAnswer: "Burna Boy",
    category: "Entertainment",
  },
  {
    question: "Which river joins the Niger at Lokoja?",
    options: ["Osun", "Gongola", "Benue", "Ogun"],
    correctAnswer: "Benue",
    category: "Geography",
  },
  {
    question: "What is the Nigerian national pledge’s first line?",
    options: [
      "I promise to serve Nigeria with all my strength",
      "To be faithful, loyal and honest",
      "I pledge to Nigeria my country",
      "To defend her unity",
    ],
    correctAnswer: "I pledge to Nigeria my country",
    category: "Culture",
  },
  {
    question: "Which Nigerian city is famous for its bronze sculptures?",
    options: ["Abuja", "Benin City", "Lagos", "Jos"],
    correctAnswer: "Benin City",
    category: "History",
  },
  {
    question: "Which state is referred to as the 'Coal City State'?",
    options: ["Enugu", "Abia", "Ebonyi", "Anambra"],
    correctAnswer: "Enugu",
    category: "Geography",
  },
  {
    question: "Who wrote the novel 'Things Fall Apart'?",
    options: [
      "Wole Soyinka",
      "Chinua Achebe",
      "Chimamanda Adichie",
      "Ben Okri",
    ],
    correctAnswer: "Chinua Achebe",
    category: "Literature",
  },
  {
    question: "Which tribe is known for the Argungu Fishing Festival?",
    options: ["Nupe", "Hausa", "Yoruba", "Igbo"],
    correctAnswer: "Hausa",
    category: "Culture",
  },
  {
    question: "What is Nigeria's international dialing code?",
    options: ["+234", "+233", "+235", "+236"],
    correctAnswer: "+234",
    category: "General Knowledge",
  },
  {
    question: "Who was the first Nigerian to win a Nobel Prize?",
    options: [
      "Chinua Achebe",
      "Wole Soyinka",
      "Nnamdi Azikiwe",
      "Buchi Emecheta",
    ],
    correctAnswer: "Wole Soyinka",
    category: "Literature",
  },
  {
    question: "What is the traditional ruler of the Yoruba people called?",
    options: ["Emir", "Oba", "Igwe", "Sarki"],
    correctAnswer: "Oba",
    category: "Culture",
  },
  {
    question: "Which animal is on the Nigerian Coat of Arms?",
    options: ["Elephant", "Horse", "Lion", "Cow"],
    correctAnswer: "Horse",
    category: "General Knowledge",
  },
  {
    question: "What is the highest mountain in Nigeria?",
    options: ["Mount Patti", "Mount Kilimanjaro", "Chappal Waddi", "Obudu"],
    correctAnswer: "Chappal Waddi",
    category: "Geography",
  },
  {
    question: "Which state is the oil-rich Niger Delta located in?",
    options: ["Borno", "Edo", "Bayelsa", "Osun"],
    correctAnswer: "Bayelsa",
    category: "Economy",
  },
  {
    question: "Which Nigerian leader declared war on Biafra in 1967?",
    options: [
      "Yakubu Gowon",
      "Olusegun Obasanjo",
      "Aguiyi Ironsi",
      "Ibrahim Babangida",
    ],
    correctAnswer: "Yakubu Gowon",
    category: "History",
  },
  {
    question: "What is the Nigerian Police emergency number?",
    options: ["911", "199", "112", "123"],
    correctAnswer: "112",
    category: "General Knowledge",
  },
  {
    question: "Who is the current Sultan of Sokoto?",
    options: [
      "Sanusi Lamido Sanusi",
      "Sa’adu Abubakar",
      "Aminu Tambuwal",
      "Ibrahim Dasuki",
    ],
    correctAnswer: "Sa’adu Abubakar",
    category: "Religion",
  },
  {
    question: "Which is Nigeria's national flower?",
    options: ["Sunflower", "Flame Tree", "Costus Spectabilis", "Hibiscus"],
    correctAnswer: "Costus Spectabilis",
    category: "Nature",
  },
  {
    question: "How many local government areas (LGAs) does Nigeria have?",
    options: ["774", "500", "888", "650"],
    correctAnswer: "774",
    category: "General Knowledge",
  },
  {
    question: "Which Nigerian airport is the busiest?",
    options: [
      "Aminu Kano International Airport",
      "Port Harcourt International",
      "Nnamdi Azikiwe International",
      "Murtala Muhammed International",
    ],
    correctAnswer: "Murtala Muhammed International",
    category: "Geography",
  },
  {
    question: "Which mineral is Nigeria known for besides oil?",
    options: ["Gold", "Diamond", "Copper", "Tin"],
    correctAnswer: "Tin",
    category: "Economy",
  },
  {
    question: "What religion is most practiced in northern Nigeria?",
    options: ["Christianity", "Islam", "Traditional", "Hinduism"],
    correctAnswer: "Islam",
    category: "Religion",
  },
  {
    question: "Who is the current president of Nigeria (as of 2023)?",
    options: [
      "Goodluck Jonathan",
      "Muhammadu Buhari",
      "Bola Ahmed Tinubu",
      "Atiku Abubakar",
    ],
    correctAnswer: "Bola Ahmed Tinubu",
    category: "Politics",
  },
  {
    question: "What is Nigeria’s international passport color?",
    options: ["Green", "Red", "Blue", "Black"],
    correctAnswer: "Green",
    category: "General Knowledge",
  },
];

const seedTrivia = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    await TriviaQuestion.deleteMany();
    await TriviaQuestion.insertMany(questions);
    console.log("✅ Trivia questions seeded!");
    mongoose.disconnect();
  } catch (err) {
    console.error("❌ Seeding error:", err);
  }
};

seedTrivia();
